FROM openjdk:11-jre
WORKDIR /api
COPY ./target/monitor-truck-0.0.1-SNAPSHOT.jar monitor-truck-0.0.1-SNAPSHOT.jar
EXPOSE 8080
EXPOSE 5005
ENTRYPOINT ["java","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005","-jar","monitor-truck-0.0.1-SNAPSHOT.jar"]
CMD ["--spring.profiles.active=dev"]