####### NGNIX alternative for prod, version 1
## stage 1
#FROM node:10-alpine as react-build
#WORKDIR /app
#COPY . ./ # --> put .git, node_modules, build in .dockerignore file!
#RUN npm install
#RUN npm run build
## stage: 2 
#FROM nginx:alpine
##COPY nginx.conf /etc/nginx/conf.d/default.conf -> if we need to customize something!
#COPY — from=react-build /app/build /usr/share/nginx/html
#EXPOSE 80
#CMD [“nginx”, “-g”, “daemon off;”]
# docker build . -t react-docker 
# docker run -p 8000:80 react-docker

####### NGNIX alternative for prod, version 2 (run build locally)
#FROM nginx:alpine
#COPY /build /usr/share/nginx/html
#EXPOSE 80
#CMD [“nginx”, “-g”, “daemon off;”]