server:
  servlet:
    context-path: /api

logging:
  level:
    root: INFO

spring:
  data:
    mongodb:
      uri: ${MONGODB_ATLAS_URI}
      auto-index-creation: true

cors:
  allowed-origins: ${CORS_ORIGINS}